# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTitle():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_title(self):
    self.driver.get("https://kick.com/")
    self.driver.set_window_size(1470, 861)
    element = self.driver.find_element(By.CSS_SELECTOR, ".carousel__slide:nth-child(11) .carousel-picture-holder > .relative > .w-full")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".grid-item:nth-child(4) > .category-banner > .relative > .w-full").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".grid-item:nth-child(4) > .category-banner > .relative > .w-full")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".grid-item:nth-child(1) > .card-thumbnail-holder > .relative > .w-full").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".grid-item:nth-child(1) > .card-thumbnail-holder > .relative > .w-full")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".border-b:nth-child(2)").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".grid-item:nth-child(1) .truncate:nth-child(2) > .text-xs").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".sidebar-item:nth-child(1) .item-name")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".border-b:nth-child(2)").click()
    self.driver.find_element(By.LINK_TEXT, "VALORANT").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".border-b:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".grid-item:nth-child(3) .truncate:nth-child(2) > .text-xs").click()
    self.driver.close()
  
