# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test18Tag():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_18Tag(self):
    # Test name: 18+ Tag
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://kick.com/")
    # 2 | setWindowSize | 1470x861 | 
    self.driver.set_window_size(1470, 861)
    # 3 | click | css=.grid-item:nth-child(4) > .category-banner > .relative > .w-full | 
    self.driver.find_element(By.CSS_SELECTOR, ".grid-item:nth-child(4) > .category-banner > .relative > .w-full").click()
    # 4 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 5 | click | css=.grid-item:nth-child(1) .category-tag-component:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".grid-item:nth-child(1) .category-tag-component:nth-child(2)").click()
    # 6 | click | css=.grid-item:nth-child(1) > .card-thumbnail-holder > .relative > .w-full | 
    self.driver.find_element(By.CSS_SELECTOR, ".grid-item:nth-child(1) > .card-thumbnail-holder > .relative > .w-full").click()
    # 7 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 8 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 9 | click | css=.grid-item:nth-child(2) > .card-thumbnail-holder > .relative > .w-full | 
    self.driver.find_element(By.CSS_SELECTOR, ".grid-item:nth-child(2) > .card-thumbnail-holder > .relative > .w-full").click()
    # 10 | mouseOver | linkText=Browse | 
    element = self.driver.find_element(By.LINK_TEXT, "Browse")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 11 | click | css=.grid-item:nth-child(3) > .card-thumbnail-holder > .relative > .w-full | 
    self.driver.find_element(By.CSS_SELECTOR, ".grid-item:nth-child(3) > .card-thumbnail-holder > .relative > .w-full").click()
    # 12 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 13 | mouseOver | linkText=Browse | 
    element = self.driver.find_element(By.LINK_TEXT, "Browse")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 14 | mouseOut | linkText=Browse | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 15 | click | linkText=VALORANT | 
    self.driver.find_element(By.LINK_TEXT, "VALORANT").click()
    # 16 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 17 | mouseOver | css=.carousel__slide:nth-child(10) .carousel-picture-holder > .relative > .w-full | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".carousel__slide:nth-child(10) .carousel-picture-holder > .relative > .w-full")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 18 | mouseOut | css=.carousel__slide:nth-child(10) .carousel-picture-holder > .relative > .w-full | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 19 | click | linkText=Dota 2 | 
    self.driver.find_element(By.LINK_TEXT, "Dota 2").click()
    # 20 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 21 | close |  | 
    self.driver.close()
  
