# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestShowmore():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_showmore(self):
    # Test name: Show more
    # Step # | name | target | value
    # 1 | open | https://kick.com/categories/games | 
    self.driver.get("https://kick.com/categories/games")
    # 2 | setWindowSize | 1470x861 | 
    self.driver.set_window_size(1470, 861)
    # 3 | mouseOver | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 4 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 5 | mouseOut | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 6 | close |  | 
    self.driver.close()
  
