# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGameNames():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_gameNames(self):
    # Test name: Game Names
    # Step # | name | target | value
    # 1 | open | https://kick.com/categories/games | 
    self.driver.get("https://kick.com/categories/games")
    # 2 | setWindowSize | 1470x862 | 
    self.driver.set_window_size(1470, 862)
    # 3 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 4 | click | linkText=League of Legends | 
    self.driver.find_element(By.LINK_TEXT, "League of Legends").click()
    # 5 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 6 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 7 | click | linkText=Call of Duty: Warzone | 
    self.driver.find_element(By.LINK_TEXT, "Call of Duty: Warzone").click()
    # 8 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 9 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 10 | mouseOver | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 11 | mouseOut | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 12 | click | linkText=Call of Duty: Modern Warfare III | 
    self.driver.find_element(By.LINK_TEXT, "Call of Duty: Modern Warfare III").click()
    # 13 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 14 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 15 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 16 | mouseOver | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 17 | mouseOut | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 18 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 19 | click | linkText=Counter-Strike 2 | 
    self.driver.find_element(By.LINK_TEXT, "Counter-Strike 2").click()
    # 20 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 21 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 22 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 23 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 24 | mouseOver | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 25 | mouseOut | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 26 | click | linkText=Destiny 2 | 
    self.driver.find_element(By.LINK_TEXT, "Destiny 2").click()
    # 27 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 28 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 29 | mouseOver | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 30 | mouseOut | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 31 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 32 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 33 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 34 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 35 | click | linkText=Rust | 
    self.driver.find_element(By.LINK_TEXT, "Rust").click()
    # 36 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 37 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 38 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 39 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 40 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 41 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 42 | mouseOver | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 43 | mouseOut | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 44 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 45 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 46 | click | linkText=Tom Clancy's Rainbow Six Siege | 
    self.driver.find_element(By.LINK_TEXT, "Tom Clancy\'s Rainbow Six Siege").click()
    # 47 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 48 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 49 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 50 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 51 | mouseOver | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 52 | mouseOut | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 53 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 54 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 55 | mouseOver | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 56 | mouseOut | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 57 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 58 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 59 | click | linkText=Overwatch 2 | 
    self.driver.find_element(By.LINK_TEXT, "Overwatch 2").click()
    # 60 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 61 | mouseOver | linkText=Browse | 
    element = self.driver.find_element(By.LINK_TEXT, "Browse")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 62 | mouseOut | linkText=Browse | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 63 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 64 | mouseOver | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 65 | mouseOut | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 66 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 67 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 68 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 69 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 70 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 71 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 72 | mouseOver | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 73 | mouseOut | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 74 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 75 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 76 | click | linkText=XDEFIANT | 
    self.driver.find_element(By.LINK_TEXT, "XDEFIANT").click()
    # 77 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 78 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 79 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 80 | mouseOver | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 81 | mouseOut | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 82 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 83 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 84 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 85 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 86 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 87 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 88 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 89 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 90 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 91 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 92 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 93 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 94 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 95 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 96 | close |  | 
    self.driver.close()
    # 97 | mouseOver | linkText=Grand Theft Auto V (GTA) | 
    element = self.driver.find_element(By.LINK_TEXT, "Grand Theft Auto V (GTA)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 98 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 99 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 100 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 101 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 102 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 103 | click | linkText=VRChat | 
    self.driver.find_element(By.LINK_TEXT, "VRChat").click()
    # 104 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 105 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 106 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 107 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 108 | mouseOver | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 109 | mouseOut | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 110 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 111 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 112 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 113 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 114 | mouseOver | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 115 | mouseOut | css=.see-more-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 116 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 117 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 118 | click | css=.see-more-btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".see-more-btn").click()
    # 119 | click | css=.mt-2 > .md\3Aoverflow-hidden | 
    self.driver.find_element(By.CSS_SELECTOR, ".mt-2 > .md\\3Aoverflow-hidden").click()
    # 120 | click | linkText=Sea of Thieves | 
    self.driver.find_element(By.LINK_TEXT, "Sea of Thieves").click()
    # 121 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 122 | close |  | 
    self.driver.close()
  
