# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLanguageFilter():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_languageFilter(self):
    # Test name: Language Filter
    # Step # | name | target | value
    # 1 | open | https://kick.com/categories/games | 
    self.driver.get("https://kick.com/categories/games")
    # 2 | setWindowSize | 1470x861 | 
    self.driver.set_window_size(1470, 861)
    # 3 | click | css=.btn-languages | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-languages").click()
    # 4 | mouseOver | css=.btn-languages | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn-languages")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | mouseOut | css=.btn-languages | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 6 | click | css=div:nth-child(11) .text-sm | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(11) .text-sm").click()
    # 7 | click | css=.justify-between | 
    self.driver.find_element(By.CSS_SELECTOR, ".justify-between").click()
    # 8 | close |  | 
    self.driver.close()
  
